/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    height: 699,
    style: 'font-family: 맑은 고딕;',
    width: 899,
    title: '분석창 보기',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    style: 'background-color:white;',
                    items: [
                        {
                            xtype: 'container',
                            height: 20
                        },
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'label',
                                    padding: 20,
                                    style: 'font-size:20px;\r\nfont-weight:bold;\r\ntext-align:center;',
                                    text: '삼성은 왜 ‘갤럭시S3 미니’ 카드를 꺼내들까 '
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 20
                        },
                        {
                            xtype: 'container',
                            height: 20,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    width: 20
                                },
                                {
                                    xtype: 'label',
                                    flex: 0,
                                    padding: 0,
                                    style: 'font-weight:bold;\r\nfont-size:15px;',
                                    width: 440,
                                    text: '실시간 방문자 추이'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 10
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    width: 20
                                },
                                {
                                    xtype: 'chart',
                                    height: 263,
                                    width: 844,
                                    animate: true,
                                    insetPadding: 0,
                                    store: 'MyArrayStore',
                                    axes: [
                                        {
                                            type: 'Category',
                                            fields: [
                                                'x'
                                            ],
                                            position: 'bottom',
                                            title: ''
                                        },
                                        {
                                            type: 'Numeric',
                                            fields: [
                                                'y'
                                            ],
                                            position: 'left',
                                            title: ''
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            xField: 'x',
                                            yField: [
                                                'y'
                                            ],
                                            smooth: 0
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 20
                        },
                        {
                            xtype: 'container',
                            height: 20,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    width: 20
                                },
                                {
                                    xtype: 'label',
                                    flex: 0,
                                    padding: 0,
                                    style: 'font-weight:bold;\r\nfont-size:15px;',
                                    width: 438,
                                    text: '방문자 유입 순위'
                                },
                                {
                                    xtype: 'container',
                                    width: 24
                                },
                                {
                                    xtype: 'label',
                                    padding: 0,
                                    style: 'font-weight:bold;\r\nfont-size:15px;',
                                    text: '방문 성향'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    border: '',
                                    height: 240,
                                    padding: 15,
                                    width: 475,
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 25,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    floating: false,
                                                    height: 34,
                                                    padding: '5,5,5,5',
                                                    style: 'vertical-align:middle;',
                                                    text: '1위 '
                                                },
                                                {
                                                    xtype: 'image',
                                                    height: 20,
                                                    width: 25,
                                                    src: 'http://profile.ak.fbcdn.net/hprofile-ak-snc6/276189_100002118681313_1988423816_q.jpg'
                                                },
                                                {
                                                    xtype: 'label',
                                                    padding: '5,5,5,5',
                                                    style: 'vertical_align:center;',
                                                    text: '오우택'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    floating: false,
                                                    height: 36,
                                                    shrinkWrap: 0,
                                                    style: 'background-color:#39B4BF;',
                                                    width: 150,
                                                    layout: {
                                                        type: 'fit'
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    padding: '5,5,5,5',
                                                    text: '40%'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            height: 25,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    floating: false,
                                                    height: 34,
                                                    padding: '5,5,5,5',
                                                    style: 'vertical-align:middle;',
                                                    text: '2위 '
                                                },
                                                {
                                                    xtype: 'image',
                                                    height: 25,
                                                    width: 25,
                                                    src: 'http://profile.ak.fbcdn.net/hprofile-ak-ash4/275023_608461498_3111514_q.jpg'
                                                },
                                                {
                                                    xtype: 'label',
                                                    padding: '5,5,5,5',
                                                    style: 'vertical_align:center;',
                                                    text: '이한솔'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    floating: false,
                                                    height: 26,
                                                    shrinkWrap: 0,
                                                    style: 'background-color:#39B4BF;',
                                                    width: 90,
                                                    autoScroll: false,
                                                    layout: {
                                                        align: 'middle',
                                                        pack: 'center',
                                                        type: 'hbox'
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    height: 50,
                                                    padding: '5,5,5,5',
                                                    text: '25%'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            height: 25,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    floating: false,
                                                    height: 34,
                                                    padding: '5,5,5,5',
                                                    style: 'vertical-align:middle;',
                                                    text: '3위 '
                                                },
                                                {
                                                    xtype: 'image',
                                                    height: 25,
                                                    width: 25,
                                                    src: 'http://profile.ak.fbcdn.net/hprofile-ak-ash4/275023_608461498_3111514_q.jpg'
                                                },
                                                {
                                                    xtype: 'label',
                                                    padding: '5,5,5,5',
                                                    style: 'vertical_align:center;',
                                                    text: '심영재'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    floating: false,
                                                    height: 26,
                                                    shrinkWrap: 0,
                                                    style: 'background-color:#39B4BF;',
                                                    width: 50,
                                                    autoScroll: false,
                                                    layout: {
                                                        align: 'middle',
                                                        pack: 'center',
                                                        type: 'hbox'
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    height: 50,
                                                    padding: '5,5,5,5',
                                                    text: '10%'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            height: 25,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    floating: false,
                                                    height: 34,
                                                    padding: '5,5,5,5',
                                                    style: 'vertical-align:middle;',
                                                    text: '4위 '
                                                },
                                                {
                                                    xtype: 'image',
                                                    height: 25,
                                                    width: 25,
                                                    src: 'http://profile.ak.fbcdn.net/hprofile-ak-ash4/275023_608461498_3111514_q.jpg'
                                                },
                                                {
                                                    xtype: 'label',
                                                    padding: '5,5,5,5',
                                                    style: 'vertical_align:center;',
                                                    text: '이희덕'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    floating: false,
                                                    height: 26,
                                                    shrinkWrap: 0,
                                                    style: 'background-color:#39B4BF;',
                                                    width: 50,
                                                    autoScroll: false,
                                                    layout: {
                                                        align: 'middle',
                                                        pack: 'center',
                                                        type: 'hbox'
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    height: 50,
                                                    padding: '5,5,5,5',
                                                    text: '10%'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            height: 25,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    floating: false,
                                                    height: 34,
                                                    padding: '5,5,5,5',
                                                    style: 'vertical-align:middle;',
                                                    text: '5위 '
                                                },
                                                {
                                                    xtype: 'image',
                                                    height: 25,
                                                    width: 25,
                                                    src: 'http://profile.ak.fbcdn.net/hprofile-ak-ash4/275023_608461498_3111514_q.jpg'
                                                },
                                                {
                                                    xtype: 'label',
                                                    padding: '5,5,5,5',
                                                    style: 'vertical_align:center;',
                                                    text: '이희덕'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    floating: false,
                                                    height: 26,
                                                    shrinkWrap: 0,
                                                    style: 'background-color:#39B4BF;',
                                                    width: 50,
                                                    autoScroll: false,
                                                    layout: {
                                                        align: 'middle',
                                                        pack: 'center',
                                                        type: 'hbox'
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    height: 50,
                                                    padding: '5,5,5,5',
                                                    text: '10%'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            height: 25,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    floating: false,
                                                    height: 34,
                                                    padding: '5,5,5,5',
                                                    style: 'vertical-align:middle;',
                                                    text: '6위'
                                                },
                                                {
                                                    xtype: 'image',
                                                    height: 25,
                                                    width: 25,
                                                    src: 'http://profile.ak.fbcdn.net/hprofile-ak-ash4/275023_608461498_3111514_q.jpg'
                                                },
                                                {
                                                    xtype: 'label',
                                                    padding: '5,5,5,5',
                                                    style: 'vertical_align:center;',
                                                    text: '이희덕'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    floating: false,
                                                    height: 26,
                                                    shrinkWrap: 0,
                                                    style: 'background-color:#39B4BF;',
                                                    width: 50,
                                                    autoScroll: false,
                                                    layout: {
                                                        align: 'middle',
                                                        pack: 'center',
                                                        type: 'hbox'
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    height: 50,
                                                    padding: '5,5,5,5',
                                                    text: '10%'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 245,
                                    padding: 10,
                                    items: [
                                        {
                                            xtype: 'radiogroup',
                                            width: 400,
                                            fieldLabel: '',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: '성별'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: '연령'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: '지역'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'chart',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 0,
                                            store: 'MyArrayStore',
                                            theme: 'Category6',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    position: 'left',
                                                    title: ''
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    position: 'bottom',
                                                    title: ''
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'bar',
                                                    label: {
                                                        display: 'insideEnd',
                                                        field: 'y',
                                                        color: '#333',
                                                        'text-anchor': 'middle'
                                                    },
                                                    axis: 'bottom',
                                                    xField: 'x',
                                                    yField: [
                                                        'y'
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});