/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.container.Container',

    layout: {
        align: 'center',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    floating: false,
                    src: '../img/logo.png'
                },
                {
                    xtype: 'panel',
                    width: 400,
                    title: 'Yog.io!',
                    items: [
                        {
                            xtype: 'container',
                            html: 'Yog.io!는 소셜 네트워크 공유-링크 분석시스템 입니다.',
                            padding: 10
                        },
                        {
                            xtype: 'container',
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    padding: 5,
                                    href: '../func/share',
                                    text: '경로 만들기'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 10px',
                                    padding: 5,
                                    text: '페이지 만들기'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 10',
                                    padding: 5,
                                    text: '분석 결과 보기'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    html: '&copy; SW Maestro 3rd SLA 팀',
                    margin: 10
                }
            ]
        });

        me.callParent(arguments);
    }

});