// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sla.model;

import sla.model.Page;

privileged aspect Page_Roo_JavaBean {
    
    public String Page.getContent() {
        return this.content;
    }
    
    public void Page.setContent(String content) {
        this.content = content;
    }
    
}
