// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sla.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import sla.model.UserAgentInfo;

privileged aspect UserAgentInfo_Roo_Jpa_Entity {
    
    declare @type: UserAgentInfo: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long UserAgentInfo.id;
    
    @Version
    @Column(name = "version")
    private Integer UserAgentInfo.version;
    
    public Long UserAgentInfo.getId() {
        return this.id;
    }
    
    public void UserAgentInfo.setId(Long id) {
        this.id = id;
    }
    
    public Integer UserAgentInfo.getVersion() {
        return this.version;
    }
    
    public void UserAgentInfo.setVersion(Integer version) {
        this.version = version;
    }
    
}
