// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sla.model;

import sla.model.UserAgentInfo;

privileged aspect UserAgentInfo_Roo_JavaBean {
    
    public long UserAgentInfo.getEncodedKeyId() {
        return this.encodedKeyId;
    }
    
    public void UserAgentInfo.setEncodedKeyId(long encodedKeyId) {
        this.encodedKeyId = encodedKeyId;
    }
    
    public int UserAgentInfo.getUseCount() {
        return this.useCount;
    }
    
    public void UserAgentInfo.setUseCount(int useCount) {
        this.useCount = useCount;
    }
    
    public String UserAgentInfo.getOperationSystem() {
        return this.operationSystem;
    }
    
    public void UserAgentInfo.setOperationSystem(String operationSystem) {
        this.operationSystem = operationSystem;
    }
    
    public String UserAgentInfo.getBrowser() {
        return this.browser;
    }
    
    public void UserAgentInfo.setBrowser(String browser) {
        this.browser = browser;
    }
    
    public String UserAgentInfo.getBrowserVersion() {
        return this.browserVersion;
    }
    
    public void UserAgentInfo.setBrowserVersion(String browserVersion) {
        this.browserVersion = browserVersion;
    }
    
}
