// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sla.model;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
import sla.model.UserAgentInfo;

privileged aspect UserAgentInfo_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager UserAgentInfo.entityManager;
    
    public static final EntityManager UserAgentInfo.entityManager() {
        EntityManager em = new UserAgentInfo().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long UserAgentInfo.countUserAgentInfoes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM UserAgentInfo o", Long.class).getSingleResult();
    }
    
    public static List<UserAgentInfo> UserAgentInfo.findAllUserAgentInfoes() {
        return entityManager().createQuery("SELECT o FROM UserAgentInfo o", UserAgentInfo.class).getResultList();
    }
    
    public static UserAgentInfo UserAgentInfo.findUserAgentInfo(Long id) {
        if (id == null) return null;
        return entityManager().find(UserAgentInfo.class, id);
    }
    
    public static List<UserAgentInfo> UserAgentInfo.findUserAgentInfoEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM UserAgentInfo o", UserAgentInfo.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void UserAgentInfo.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void UserAgentInfo.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            UserAgentInfo attached = UserAgentInfo.findUserAgentInfo(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void UserAgentInfo.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void UserAgentInfo.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public UserAgentInfo UserAgentInfo.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        UserAgentInfo merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
