// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sla.model;

import org.springframework.beans.factory.annotation.Configurable;
import sla.model.VisitCount;

privileged aspect VisitCount_Roo_Configurable {
    
    declare @type: VisitCount: @Configurable;
    
}
